services:
  postgres:
    image: "postgres:17"
    container_name: mypostgres_container
    environment:
      - POSTGRES_DB=linkdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: "no"
    networks:
      - appnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d linkdb" ]
      interval: 30s
      timeout: 10s
      retries: 5

  spring-app:
    build: .
    container_name: app_container
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/linkdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pgpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: "no"
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge